const products=[
{slug:"brand-studio",tag:"AI 创作",name:"Brand Studio",title:"一句话生成完整品牌视觉，而不是只生成一张图",image:"https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1600&q=85",summary:"面向创业者、运营和小团队，把品牌命名、视觉方向、社交媒体封面与基础物料整合成一次完整交付。真正的卖点不是模型更强，而是把分散的设计步骤压缩成一个可复用项目。",audience:["创业者","品牌设计师","内容创作者"],insight:"用户购买的是从想法到可发布资产的完整结果。AI 创作产品的竞争会从单次生成，转向项目一致性、可编辑性和复用。",sourceUrl:""},
{slug:"video-flow",tag:"AI 视频",name:"Video Flow",title:"从脚本到成片，让普通人五分钟完成第一条视频",image:"https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=1600&q=85",summary:"它把镜头拆分、配音、字幕、音乐和转场放进同一流程，体验更像轻量版剪辑工作台，而不是专业生成工具。产品价值在于帮助用户更快发布，而不是给出更多参数。",audience:["短视频创作者","市场运营","小商家"],insight:"决定留存的关键是第一次发布成功率。最有效的 Onboarding 不是功能教学，而是让用户快速完成并分享第一件作品。",sourceUrl:""},
{slug:"shared-memory",tag:"AI Workspace",name:"Shared Memory",title:"让多个 AI 工具共享项目背景，而不是重复解释",image:"https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1600&q=85",summary:"它帮助产品经理、设计师和开发者减少重复解释，让项目目标、历史决策和当前状态在多个 AI 工具之间保持一致。重点不是保存聊天记录，而是维护持续更新的项目记忆。",audience:["产品经理","开发者","创业团队"],insight:"AI 工作台的长期价值来自越用越懂项目。真正值得沉淀的是状态、决策和偏好，而不是海量对话。",sourceUrl:""},
{slug:"shopping-guide",tag:"AI Shopping",name:"Shopping Guide",title:"从商品搜索升级为真正的购买决策助手",image:"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1600&q=85",summary:"用户只需描述预算、场景和偏好，产品会整理候选商品、提炼评价分歧并解释推荐理由。它减少的不是搜索时间，而是比较与决策疲劳。",audience:["普通消费者","高频网购用户"],insight:"Shopping Agent 的核心不是推荐更多商品，而是帮助用户更有信心地做决定。可解释推荐会比无限商品流更重要。",sourceUrl:""},
{slug:"delivery-qa",tag:"AI Coding",name:"Delivery QA",title:"AI 写完代码后，继续运行、测试并修复",image:"https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1600&q=85",summary:"面向独立开发者和产品团队，把生成代码、启动应用、模拟用户操作与错误修复串成闭环。用户真正愿意付费的不是代码字符数，而是这个功能能不能直接用。",audience:["独立开发者","产品团队","创业公司"],insight:"Coding Agent 应从助手升级成负责交付的协作者。界面需要持续显示当前状态、风险和下一步，而不是只展示对话。",sourceUrl:""},
{slug:"voice-companion",tag:"AI Voice",name:"Voice Companion",title:"能被打断、会停顿、理解语气的实时语音助手",image:"https://images.unsplash.com/photo-1589254065878-42c9da997008?auto=format&fit=crop&w=1600&q=85",summary:"新一代语音产品开始围绕连续对话、情绪感知和自然轮次设计体验，更适合陪伴、通勤和轻任务场景。它们不再要求用户先学会如何对 AI 下指令。",audience:["普通用户","车载用户","语言学习者"],insight:"语音体验的突破点不是回答更快，而是让用户感觉不需要适应机器。打断、沉默和语气反馈都是核心产品能力。",sourceUrl:""}
];
export const issues=[{slug:"2026-07-18",isoDate:"2026-07-18",dateLabel:"2026年7月18日",weekday:"星期六",oneSentence:"AI 正从展示能力，转向替用户完成一件真实的事。",products,productOfTheDay:{name:"Shared Memory",tagline:"让多个 AI 共享同一个项目，而不是共享一堆聊天记录。",image:"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1800&q=90",analysis:[{title:"核心场景",text:"团队在多个 AI 工具间切换时，不再重复解释项目目标、历史决策与当前进度。"},{title:"为什么每天打开",text:"记忆持续积累，每一次使用都在降低下一次使用成本。"},{title:"关键交互",text:"记忆在需要时自然出现；用户能查看来源、修正事实并控制读取权限。"},{title:"商业模式",text:"个人订阅叠加团队协作、权限、审计与私有部署。"}],takeaway:"项目状态、用户偏好与历史决策，比聊天记录本身更能形成长期留存。"},trends:[{title:"AI 开始交付完整结果",text:"用户希望 AI 完成从输入、处理、校验到发布的完整任务。"},{title:"Workspace 替代单一聊天框",text:"项目、文件、记忆、任务状态和协作角色正在成为主界面。"},{title:"不用学习，成为最强体验优势",text:"优秀产品越来越少讲模型参数，而是直接展示用户现在能完成什么。"}]},{slug:"2026-07-17",isoDate:"2026-07-17",dateLabel:"2026年7月17日",weekday:"星期五",oneSentence:"AI 产品的竞争焦点，正在从生成质量转向任务完成率。",products:products.slice(0,4),productOfTheDay:null,trends:[]}];
export const getLatestIssue=()=>issues[0];
export const getIssue=(slug)=>issues.find(x=>x.slug===slug);
